CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    base_month VARCHAR(7) NOT NULL,
    status VARCHAR(32) NOT NULL
);

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    bank_name VARCHAR(255) NOT NULL,
    account_name VARCHAR(255) NOT NULL,
    balance BIGINT NOT NULL,
    purpose VARCHAR(255),
    included_in_assets BOOLEAN NOT NULL,
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    card_company VARCHAR(255) NOT NULL,
    card_name VARCHAR(255) NOT NULL,
    payment_day INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_cards_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    category_type VARCHAR(32) NOT NULL,
    system_default BOOLEAN NOT NULL,
    CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    transaction_date DATE NOT NULL,
    merchant VARCHAR(255) NOT NULL,
    amount BIGINT NOT NULL,
    transaction_type VARCHAR(32) NOT NULL,
    category_id BIGINT,
    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE financial_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    amount BIGINT NOT NULL,
    direction VARCHAR(32) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    fixed BOOLEAN NOT NULL,
    CONSTRAINT fk_financial_events_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE recurring_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    recurrence_type VARCHAR(32) NOT NULL,
    day_of_month INTEGER,
    start_date DATE NOT NULL,
    end_date DATE,
    amount BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    direction VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_recurring_rules_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE monthly_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    budget_month VARCHAR(7) NOT NULL,
    total_limit_amount INTEGER NOT NULL,
    CONSTRAINT fk_monthly_budgets_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_monthly_budgets_user_month UNIQUE (user_id, budget_month)
);

CREATE TABLE budget_category_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_id BIGINT NOT NULL,
    category_name VARCHAR(255) NOT NULL,
    limit_amount INTEGER NOT NULL,
    CONSTRAINT fk_budget_category_limits_budget FOREIGN KEY (budget_id) REFERENCES monthly_budgets(id)
);

CREATE TABLE agent_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_agent_conversations_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE agent_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    content VARCHAR(4000) NOT NULL,
    sources VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_agent_messages_conversation FOREIGN KEY (conversation_id) REFERENCES agent_conversations(id)
);

CREATE INDEX idx_accounts_user ON accounts(user_id);
CREATE INDEX idx_cards_user ON cards(user_id);
CREATE INDEX idx_categories_user ON categories(user_id);
CREATE INDEX idx_transactions_user_date ON transactions(user_id, transaction_date);
CREATE INDEX idx_financial_events_user_date ON financial_events(user_id, event_date);
CREATE INDEX idx_recurring_rules_user ON recurring_rules(user_id);
CREATE INDEX idx_agent_messages_conversation ON agent_messages(conversation_id, created_at);
