CREATE TABLE api_request_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    method VARCHAR(16) NOT NULL,
    path VARCHAR(1000) NOT NULL,
    status INTEGER NOT NULL,
    duration_ms BIGINT NOT NULL,
    client_ip VARCHAR(128),
    user_agent VARCHAR(1000),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_api_request_logs_created_at ON api_request_logs(created_at);
CREATE INDEX idx_api_request_logs_path_status ON api_request_logs(path, status);
CREATE INDEX idx_api_request_logs_user_created ON api_request_logs(user_id, created_at);
